server {
    listen 80;
    listen [::]:80;
    server_name wikdra.top www.wikdra.top;
    root /var/lib/nginx/html;
    index index.html index.php;

    location /bichu {
        try_files $uri $uri/ /bichu.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name panele.wikdra.top;
    root /var/lib/nginx/html;
    index panels.html;

    error_page 404 /404.html;
    location = /404.html {
        root /var/lib/nginx/html;
        internal;
    }
}
